-- Clash of Cards seed data
-- Changes cards uniqueness from name-only to (name, category).

ALTER TABLE cards DROP INDEX name;
ALTER TABLE cards ADD UNIQUE KEY uq_cards_name_category (name, category);

INSERT INTO cards (name, category, required_qty) VALUES
('Barbarian','Elixir',1),
('Archer','Elixir',1),
('Giant','Elixir',1),
('Goblin','Elixir',1),
('Wall Breaker','Elixir',1),
('Balloon','Elixir',1),
('Wizard','Elixir',1),
('Healer','Elixir',1),
('Dragon','Elixir',1),
('P.E.K.K.A','Elixir',1),
('Baby Dragon','Elixir',1),
('Miner','Elixir',1),
('Electro Dragon','Elixir',1),
('Yeti','Elixir',1),
('Dragon Rider','Elixir',1),
('Electro Titan','Elixir',1),
('Root Rider','Elixir',1),
('Thrower','Elixir',1),
('Meteor Golem','Elixir',1),
('Minion','Dark Elixir',1),
('Hog Rider','Dark Elixir',1),
('Valkyrie','Dark Elixir',1),
('Golem','Dark Elixir',1),
('Witch','Dark Elixir',1),
('Lava Hound','Dark Elixir',1),
('Bowler','Dark Elixir',1),
('Ice Golem','Dark Elixir',1),
('Headhunter','Dark Elixir',1),
('Apprentice Warden','Dark Elixir',1),
('Druid','Dark Elixir',1),
('Furnace','Dark Elixir',1),
('Ruin Witch','Dark Elixir',1),
('Raged Barbarian','Builder Base',1),
('Sneaky Archer','Builder Base',1),
('Boxer Giant','Builder Base',1),
('Beta Minion','Builder Base',1),
('Bomber','Builder Base',1),
('Baby Dragon','Builder Base',1),
('Cannon Cart','Builder Base',1),
('Night Witch','Builder Base',1),
('Drop Ship','Builder Base',1),
('Power P.E.K.K.A','Builder Base',1),
('Hog Glider','Builder Base',1),
('Super Barbarian','Super',1),
('Super Archer','Super',1),
('Super Giant','Super',1),
('Sneaky Goblin','Super',1),
('Super Wall Breaker','Super',1),
('Rocket Balloon','Super',1),
('Super Wizard','Super',1),
('Super Dragon','Super',1),
('Inferno Dragon','Super',1),
('Super Miner','Super',1),
('Super Yeti','Super',1),
('Super Minion','Super',1),
('Super Hog Rider','Super',1),
('Super Valkyrie','Super',1),
('Super Witch','Super',1),
('Ice Hound','Super',1),
('Super Bowler','Super',1)
ON DUPLICATE KEY UPDATE required_qty = VALUES(required_qty);
